### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by ummeegge** [NetSPI/NetblockTool#10]
Dear developers,
wanted to leave a note for requirements.txt, after building v2.1.0, installing and starting NetblockTool on an IPFire environment i got some 'ModuleNotFoundError's  for edgar, requests and idna .

Hope this is helpful for you.

Best,

Erik

**Comment by venominfosec** [comment]
Hello,

This repository contains a file called requirements.txt that specifies the necessary Python libraries that need to be installed for NetblockTool to work properly. The requests library specified is in this file. You can install all necessary dependencies using the command `pip3 install -r requirements.txt`. 

The edgar library has custom modifications and should not be installed using pip. Instead, ensure that NetblockTool.py and the edgar directory from this repository are in the same directory when running the script.

The idna library is installed when installing pip (tested on Ubuntu 22.04, pip 22.0.2, Python 3.10.12).
