### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by dvershinin** [NetSPI/NetblockTool#4]
I would like to contribute by packaging RPMs for this project to facilitate easy installation on CentOS/RHEL.

However, there are no release versions added. Can you please consider [tagging a release](https://github.com/NetSPI/NetblockTool/releases)?

Great work on NetblockTool.

**Comment by venominfosec** [comment]
Just added a release: https://github.com/NetSPI/NetblockTool/releases/tag/v2.0.0
