### ISSUE TITLE
Search by mnt-by

### ISSUE THREAD

**Issue by billsargent** [NetSPI/NetblockTool#6]
Is it possible to search by mnt-by?

My mail server is being attacked by tons of IP blocks with the mnt-by as "ashitt".  I've tried a RIPE search on the ripe database query page but I'm not coming up with anything. Each time I look at the spam, it's by IP blocks where there are 50-100 all from the same block. If i could get a list of all ip blocks by that ashitt thing, I could probably keep this person or botnet from attacking.

**Comment by venominfosec** [comment]
This is not within the scope of what this tool was designed for. Closing issue.
